// Copyright VanstySanic. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "UObject/Object.h"

namespace EVSMovementMode
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NavWalking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying);
	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MantlingOrVaulting);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRunning);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FixedPointLeap);
}

namespace EVSOrientationEvaluateType
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);

	/** Just returns the pawn's rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Self);

	/** If zero, return the character rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Velocity);

	/** If zero, return the character rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
		
	/** Including velocity and input. Velocity takes higher priority. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement);
	
	/** Returns the pawn's control rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control);
	
	/** Returns the pawn's view rotation, */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(View);

	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aim_Component);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aim_Point);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aim_Direction);
}

namespace EVSStance
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Squatting);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crawling);
}

namespace EVSGait
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
}


namespace EVSMovementState
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurnInPlace);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LandRecovery);
}

namespace EVSWallRunState
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Starting);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cycling);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ending);
}

namespace EVSMovementEvent
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_MovementMode);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_Stance);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_Gait);
	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Jump);
	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TurnInPlace_Start);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TurnInPlace_Connect);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TurnInPlace_End);
	
	// VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TurnInPlace);
	// VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_LandRecovery);
}