// Copyright VanstySanic. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "UObject/Object.h"

namespace EVSMovementMode
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NavWalking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swimming);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flying);
	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRunning);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FixedPointLeap);
}

namespace EVSOrientationEvaluateType
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);

	/** Just returns the pawn's rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Self);

	/** If zero, return the character rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Velocity);

	/** If zero, return the character rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
		
	/** Including velocity and input. Velocity takes higher priority. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement);
	
	/** Returns the pawn's control rotation. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control);
	
	/** Returns the pawn's view rotation, */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(View);

	/** Orient towards a given point. */
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming);
}

namespace EVSStance
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crawling);
}

namespace EVSGait
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jogging);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
}


namespace EVSMovementState
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurnInPlace);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LandRecovery);

	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRun_Start);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallRun_Finish);
}

namespace EVSMovementNotify
{
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_MovementMode);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_Stance);
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateChange_Gait);
	
	VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Jump);
	// VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_TurnInPlace);
	// VSMOVEMENTSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_LandRecovery);
}