// Copyright VanstySanic. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "UObject/Object.h"

namespace EVSAnimDirection
{
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(XX);
	
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FX);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BX);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(XL);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(XR);

	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FL);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FR);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BL);
	VSMOVEMENTANIM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BR);
}

////////////////
