// Copyright VanstySanic. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"
#include "UObject/Object.h"

/** Canonical gameplay tags used to identify built-in setting items. */
namespace EVSSettingItem
{
	namespace Video
	{
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WindowMode);
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScreenResolution);
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VSync);
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrameRateLimit);
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monitor);
	}
	
	namespace Scalability
	{
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ResolutionScale);
			
		namespace QualityLevel
		{
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDistance);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AntiAliasing);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shadow);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GlobalIllumination);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reflection);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PostProcess);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Texture);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VisualEffect);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foliage);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shading);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Landscape);
		}
	}

	namespace Graphics
	{
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionBlur);
		VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AntiAliasingMethod);
	}

	namespace Audio
	{
		namespace Volume
		{
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Master);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Music);
		}

		namespace Device
		{
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Output);
			VSSETTINGSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
		}
	}
}
